### ISSUE TITLE
How good it is for production?

### ISSUE THREAD

**Issue by Mdslino** [Relrin/sanic-pw#1]
@Relrin can i use this in production?

**Comment by Relrin** [comment]
Hello, @Mdslino 

Thank you for opening an issue here.

Honestly saying, I'm more inclined to the option "no", because I had made it for my own personal / pet projects, which are not intended for using in production. Moreover, keep in mind, that this package is compatible only with Peewee 2.10.* versions, because [the main dependency](https://github.com/klen/peewee_migrate) isn't working with Peewee 3.0+ (at least for now)

**Comment by Mdslino** [comment]
Thanks. I'll follow the project, maybe one day i can help with it.
